### ISSUE TITLE
Content blocked

### ISSUE THREAD

**Issue by Jeffrey-IKUU** [vinubabu323/website-preview#11]
Installing this plugin does create a preview button beneath the custom field, which does open a modal. Inside the modal I see a 'content blocked' warning. In my console there is a
Refused to frame 'http://localhost:3000/' because it violates the following Content Security Policy directive: "default-src 'self'".

**Comment by vinubabu323** [comment]
Hi jeffrey,

By default the plugin supports only your localhost URL if you want to add any another URL you need to change the middlewares.js file as follows.

`module.exports = [
  'strapi::errors',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'frame-src':["'self'","YOUR_URL"],
          'frame-ancestors': null,
          upgradeInsecureRequests: null,
        },
      },
      frameguard: false,
    },


  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];`

Add your URL 'http://localhost:3000/' into frame-src and try.

Thankyou.

**Comment by Jeffrey-IKUU** [comment]
Thank you for your quick reply!

This did the trick!

One small suggestion here:
`Add your URL 'http://localhost:3000/' into frame-src and try.`

Adding `process.env.FRONT_END_URL` is a better solution here.

**Comment by vinubabu323** [comment]
Thank you for your suggestion that will also work.

**Comment by nobleach** [comment]
Trying this but it's still giving me: ```Refused to frame 'http://localhost:4321/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.```
My `middlewares.ts` looks like this: 

```
export default [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "frame-src": ["'self'", "http://localhost:4321/"],
          "frame-ancestors": null,
          upgradeInsecureRequests: null,
        },
      },
      frameguard: false,
    },
  },
  "strapi::security",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

It's odd that it's not even seeing that `frame-src` directive at all.
