### ISSUE TITLE
Support Node 20.x.x

### ISSUE THREAD

**Issue by scot875** [vinubabu323/website-preview#15]
Hello, would love to use this plug in with the latest strapi.. I'm currently running:
Strapi version
v4.15.4
node version
v20.10.0

Can this project be updated to run with Node 20.x?

Thanks!

**Comment by scot875** [comment]
Hello, is there any possibility of getting this done or scheduled?  Thanks!

**Comment by vinubabu323** [comment]
Can you please provide the error

**Comment by vinubabu323** [comment]
Also please see the updated readme and do the changes

**Comment by truuman** [comment]
That's because in the plugin's `package.json` the engine is specified: https://github.com/vinubabu323/website-preview/blob/master/package.json#L23

Is there any particular reason why node >=20 is unsupported?

```
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

This error happened while installing a direct dependency of /home/node/app

Your Node version is incompatible with "registry.npmjs.org/strapi-plugin-website-preview/1.0.7".

Expected version: >=14.19.1 <=18.x.x
Got: v20.11.1

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
Progress: resolved 10, reused 10, downloaded 0, added 0
```

**Comment by ssm0801** [comment]
Is therey any specific reason of using node >=14.19.1 <=18.x.x ?

@vinubabu323

**Comment by vinubabu323** [comment]
Hi it is updated
