### ISSUE TITLE
ReferenceError: FRONT_END_URL

### ISSUE THREAD

**Issue by lokesh1253** [vinubabu323/website-preview#16]
Hi @vinubabu323 when i followed all the steps given in the docuemntion , i am getting console error as ReferenceError: FRONT_END_URL is not defined

i can see preview button once clicked on it getting this error 

<img width="1502" alt="Screenshot 2024-02-22 at 4 01 37 PM" src="https://github.com/vinubabu323/website-preview/assets/108736774/2aa78a03-e651-4e76-9fd3-9876d7f5b26b">

**Comment by vinubabu323** [comment]
Please install latest version and change the .env variable as mentioned in the readme
