### ISSUE TITLE
error: Cannot read properties of undefined (reading 'register')

### ISSUE THREAD

**Issue by abisewski** [vinubabu323/website-preview#9]
Hi!

Im trying to install your plugin but Im getting the following error when I try to install the package:

`debug: ⛔️ Server wasn't able to start properly.
error: Cannot read properties of undefined (reading 'register')`

I have latest Strapi version and using 1.22.15 yarn version

**Comment by vinubabu323** [comment]
Hi,
 
I used identical versions of yarn and strapi and I didn't get the error. Please check which file the error is occurring. I think it is a problem with your server restart the server also build the project before running.
